// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FootballLeague.Models
{
    public partial class Goal
    {
        [Key]
        public int goal_id { get; set; }
        public int match_id { get; set; }
        public int team { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string player { get; set; }
        public int minute { get; set; }

        [ForeignKey("match_id")]
        [InverseProperty("Goals")]
        public virtual Match match { get; set; }
    }
}