// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FootballLeague.Models
{
    public partial class Player
    {
        [Key]
        public int player_id { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string name { get; set; }
        public int position { get; set; }
        public int team { get; set; }
        public int number { get; set; }

        [ForeignKey("position")]
        [InverseProperty("Players")]
        public virtual PlayerPosition positionNavigation { get; set; }
        [ForeignKey("team")]
        [InverseProperty("Players")]
        public virtual Team teamNavigation { get; set; }
    }
}