// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FootballLeague.Models
{
    public partial class Referee
    {
        public Referee()
        {
            Matches = new HashSet<Match>();
        }

        [Key]
        public int referee_id { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string name { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string position { get; set; }

        [InverseProperty("main_refereeNavigation")]
        public virtual ICollection<Match> Matches { get; set; }
    }
}