// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FootballLeague.Models
{
    public partial class Team
    {
        public Team()
        {
            Matchteam_1Navigations = new HashSet<Match>();
            Matchteam_2Navigations = new HashSet<Match>();
            Players = new HashSet<Player>();
        }

        [Key]
        public int team_id { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string name { get; set; }

        [InverseProperty("team_1Navigation")]
        public virtual ICollection<Match> Matchteam_1Navigations { get; set; }
        [InverseProperty("team_2Navigation")]
        public virtual ICollection<Match> Matchteam_2Navigations { get; set; }
        [InverseProperty("teamNavigation")]
        public virtual ICollection<Player> Players { get; set; }
    }
}